### ISSUE TITLE
New range syntax

### ISSUE THREAD

**Issue by ken-morel** [asxez/stove#1]
Good day Sir. Looked at your project `stove`, and looks nice and usable. Well, did not get yet what it got of special(It's in C), but just had a proposition.

I have worked on a somehow similar project, And a feature got there were slices(or range in this case).

Imagine instead of saying `from..to`, someone could say `from:to`, or `from:to:step`, that increases possibilities(as when you need to increase i of several units, just an example) or permitting you to easily enter negative ranges, hope helps!

**Comment by asxez** [comment]
> Good day Sir. Looked at your project `stove`, and looks nice and usable. Well, did not get yet what it got of special(It's in C), but just had a proposition.
> 
> I have worked on a somehow similar project, And a feature got there were slices(or range in this case).
> 
> Imagine instead of saying `from..to`, someone could say `from:to`, or `from:to:step`, that increases possibilities(as when you need to increase i of several units, just an example) or permitting you to easily enter negative ranges, hope helps!

Thank you for your issue, I would like to answer here: the range object can grow negatively, you just need to make "from" less than "to"(see the primRangeIterate function in vm/core.c), but the step size is not implemented, you can improve it according to the existing source code(vm/core.c).
